name: lume-distgen-impact-cu-inj
channels:
  - conda-forge
dependencies:
  - prefect<2.0 # until lume-services registered with conda
  - numpy
  - scikit-image
  - lume-impact
  - distgen
  - pandas
  - pip 
  - lume-model>=1.4.6
  - pip: 
    - git+https://github.com/slaclab/lume-services.git@main
